[2025-04-09T13:25:02.393+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T13:25:02.404+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-04-09T13:17:33.637256+00:00 [queued]>
[2025-04-09T13:25:02.415+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-04-09T13:17:33.637256+00:00 [queued]>
[2025-04-09T13:25:02.416+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-04-09T13:25:02.438+0000] {taskinstance.py:2890} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2025-04-09 13:17:33.637256+00:00
[2025-04-09T13:25:02.446+0000] {standard_task_runner.py:72} INFO - Started process 23289 to run task
[2025-04-09T13:25:02.452+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'is_weather_api_ready', 'manual__2025-04-09T13:17:33.637256+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpcyoy33q_']
[2025-04-09T13:25:02.453+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask is_weather_api_ready
[2025-04-09T13:25:02.493+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.is_weather_api_ready manual__2025-04-09T13:17:33.637256+00:00 [running]> on host ip-172-31-10-226.eu-north-1.compute.internal
[2025-04-09T13:25:02.748+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T13:17:33.637256+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T13:17:33.637256+00:00'
[2025-04-09T13:25:02.750+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-09T13:25:02.750+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-09T13:25:02.750+0000] {logging_mixin.py:190} INFO - Current task name:is_weather_api_ready state:running start_date:2025-04-09 13:25:02.405387+00:00
[2025-04-09T13:25:02.750+0000] {logging_mixin.py:190} INFO - Dag name:weather_dag and current dag run status:running
[2025-04-09T13:25:02.751+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T13:25:02.751+0000] {baseoperator.py:423} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-04-09T13:25:02.751+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:25:02.757+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:25:02.860+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:25:02.860+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:25:22.077+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-09T13:25:22.082+0000] {process_utils.py:132} INFO - Sending 15 to group 23289. PIDs of all processes in the group: [23289]
[2025-04-09T13:25:22.082+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 23289
[2025-04-09T13:25:22.083+0000] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-09T13:25:22.087+0000] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/ubuntu/airflow_venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 169, in execute
    return super().execute(context=context)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sensors/base.py", line 337, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-04-09T13:25:22.092+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 169, in execute
    return super().execute(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sensors/base.py", line 337, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-04-09T13:25:22.095+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-09T13:25:22.095+0000] {logging_mixin.py:190} INFO - Task start:2025-04-09 13:25:02.405387+00:00 end:2025-04-09 13:25:22.095153+00:00 duration:19.689766
[2025-04-09T13:25:22.096+0000] {logging_mixin.py:190} INFO - Task:<Task(HttpSensor): is_weather_api_ready> dag:<DAG: weather_dag> dagrun:<DagRun weather_dag @ 2025-04-09 13:17:33.637256+00:00: manual__2025-04-09T13:17:33.637256+00:00, state:running, queued_at: 2025-04-09 13:17:33.653476+00:00. externally triggered: True>
[2025-04-09T13:25:22.096+0000] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2025-04-09T13:25:22.096+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=is_weather_api_ready, run_id=manual__2025-04-09T13:17:33.637256+00:00, execution_date=20250409T131733, start_date=20250409T132502, end_date=20250409T132522
[2025-04-09T13:25:22.122+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-09T13:25:22.138+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=23289, status='terminated', exitcode=2, started='13:25:02') (23289) terminated with exit code 2
