[2025-04-09T18:04:16.453+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T18:04:16.470+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2025-04-09T18:01:53.618245+00:00 [queued]>
[2025-04-09T18:04:16.483+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2025-04-09T18:01:53.618245+00:00 [queued]>
[2025-04-09T18:04:16.483+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 3
[2025-04-09T18:04:16.500+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2025-04-09 18:01:53.618245+00:00
[2025-04-09T18:04:16.513+0000] {standard_task_runner.py:72} INFO - Started process 1607 to run task
[2025-04-09T18:04:16.518+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'manual__2025-04-09T18:01:53.618245+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpqj_7t0ka']
[2025-04-09T18:04:16.520+0000] {standard_task_runner.py:105} INFO - Job 125: Subtask transform_load_weather_data
[2025-04-09T18:04:16.568+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data manual__2025-04-09T18:01:53.618245+00:00 [running]> on host ip-172-31-10-226.eu-north-1.compute.internal
[2025-04-09T18:04:16.646+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T18:01:53.618245+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T18:01:53.618245+00:00'
[2025-04-09T18:04:16.647+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-09T18:04:16.648+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-09T18:04:16.648+0000] {logging_mixin.py:190} INFO - Current task name:transform_load_weather_data state:running start_date:2025-04-09 18:04:16.470808+00:00
[2025-04-09T18:04:16.648+0000] {logging_mixin.py:190} INFO - Dag name:weather_dag and current dag run status:running
[2025-04-09T18:04:16.648+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T18:04:16.654+0000] {logging_mixin.py:190} INFO - Data received:  {'coord': {'lon': 12.2797, 'lat': 46.7406}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'base': 'stations', 'main': {'temp': 278.12, 'feels_like': 277.28, 'temp_min': 278.12, 'temp_max': 278.12, 'pressure': 1021, 'humidity': 81, 'sea_level': 1021, 'grnd_level': 816}, 'visibility': 10000, 'wind': {'speed': 1.34, 'deg': 15, 'gust': 1.26}, 'clouds': {'all': 82}, 'dt': 1744221719, 'sys': {'country': 'IT', 'sunrise': 1744173272, 'sunset': 1744220995}, 'timezone': 7200, 'id': 3168508, 'name': 'Innichen', 'cod': 200}
[2025-04-09T18:04:17.011+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 114, in _error_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/aiobotocore/client.py", line 412, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow/dags/weather_dag.py", line 46, in transform_load_data
    df_data.to_csv(f"s3://etll/{dt_string}.csv", index=False, storage_options=aws_credentials)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py", line 157, in __exit__
    self.close()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py", line 144, in close
    handle.close()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/spec.py", line 2178, in close
    self.flush(force=True)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/spec.py", line 2041, in flush
    if self._upload_chunk(final=force) is not False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2451, in _upload_chunk
    self.commit()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2476, in commit
    write_result = self._call_s3("put_object", **kw)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2311, in _call_s3
    return self.fs.call_s3(method, self.s3_additional_kwargs, *kwarglist, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
                ^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 371, in _call_s3
    return await _error_wrapper(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 146, in _error_wrapper
    raise err
PermissionError: The provided token has expired.
[2025-04-09T18:04:17.059+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-09T18:04:17.059+0000] {logging_mixin.py:190} INFO - Task start:2025-04-09 18:04:16.470808+00:00 end:2025-04-09 18:04:17.058460+00:00 duration:0.587652
[2025-04-09T18:04:17.060+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_load_weather_data> dag:<DAG: weather_dag> dagrun:<DagRun weather_dag @ 2025-04-09 18:01:53.618245+00:00: manual__2025-04-09T18:01:53.618245+00:00, state:running, queued_at: 2025-04-09 18:01:53.642143+00:00. externally triggered: True>
[2025-04-09T18:04:17.060+0000] {logging_mixin.py:190} INFO - Failure caused by The provided token has expired.
[2025-04-09T18:04:17.060+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=manual__2025-04-09T18:01:53.618245+00:00, execution_date=20250409T180153, start_date=20250409T180416, end_date=20250409T180417
[2025-04-09T18:04:17.463+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-09T18:04:17.464+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 125 for task transform_load_weather_data (The provided token has expired.; 1607)
Traceback (most recent call last):
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 114, in _error_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/aiobotocore/client.py", line 412, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow/dags/weather_dag.py", line 46, in transform_load_data
    df_data.to_csv(f"s3://etll/{dt_string}.csv", index=False, storage_options=aws_credentials)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py", line 157, in __exit__
    self.close()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py", line 144, in close
    handle.close()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/spec.py", line 2178, in close
    self.flush(force=True)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/spec.py", line 2041, in flush
    if self._upload_chunk(final=force) is not False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2451, in _upload_chunk
    self.commit()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2476, in commit
    write_result = self._call_s3("put_object", **kw)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2311, in _call_s3
    return self.fs.call_s3(method, self.s3_additional_kwargs, *kwarglist, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
                ^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 371, in _call_s3
    return await _error_wrapper(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 146, in _error_wrapper
    raise err
PermissionError: The provided token has expired.
[2025-04-09T18:04:17.502+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-09T18:04:17.536+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T18:04:17.537+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
